services:
  - type: web
    name: certificate-generator-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    scaling:
      minInstances: 1
      maxInstances: 3
    autoDeploy: true
    healthCheckPath: /api/health